name: Terraform Deploy

# trigger when workflow should start
on: 
  # automated trigger, mostly it's going to be "git push" or merge PR, whenever change
  # happens on one of these branches:
  push:
    branches:
      - 'main'
      - 'staging'
      - 'feature/**'

permissions:
  id-token: write
  contents: read

# what exactly git should to run
jobs: 
  deploy:
    # where the job should run
    runs-on: ubuntu-latest

    steps:
      # run: |
      #   git clone git@github.com:VadimKuz-c/test.git

      # raplaces all above:
    - name: Clone repo
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: v1.9.7

    - name: Assuming the role for gha-runner
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: us-east-1
        role-to-assume: arn:aws:iam::021891614876:role/gha-runners-demo-role
        role-session-name: MySessionName
      
    - name: Terraform deploy
      working-directory: root-terraform-git-module
      run: |
        terraform init
        terraform plan 
        terraform destroy -auto-approve
